### ISSUE TITLE
How can i use this?

### ISSUE THREAD

**Issue by Drakaroft** [xtreme3d/xtreme3d#53]
Hi guys, i saw the project and the related screen and i wanted to give it a try, but i didn't understand pretty much from the website because i don't speak russian.
How does this work? Is it a standalone engine or does it require Game Maker? There are Example?
Thank you!

**Comment by gecko0307** [comment]
It is a standalone DLL which you can use in any language, not just GM. You will only have to manage your own window, with SDL or something. Currently there are no up-to-date bindings for other languages, but I'm planning to make them.

**Comment by Drakaroft** [comment]
Understood, thanks! :)
